### ISSUE TITLE
TCP services through consul service mesh broken in rc1

### ISSUE THREAD

**Issue by dani** [traefik/traefik#10448]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I expose a mariadb instance from Traefik. It's running on a Nomad cluster, and the dynamic config is the consul catalog. I use a dedicated entrypoint on Traefik. The particularity is that this mariadb is reached through the consul service mesh. The service is exposed using these tags

```
        "traefik.enable=true",
        "traefik.tcp.routers.mariadb.entrypoints=mariadb",
        "traefik.tcp.routers.mariadb.rule=HostSNI(`*`)"
```

With Traefik 3.0.0-beta5, everything is working nicely. With rc1, I can't connect to my mariadb service (timeout. Traefik is responding to the TCP connection, but it doesn't seem to route it through the service mesh, mariadb sees nothing)

### What did you see instead?

Timeout when trying to connect to my mariadb service. Only TCP services seem affected, I expose a lot of other HTTP services through the mesh without any issue.

### What version of Traefik are you using?

```
Version:      3.0.0-rc1
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-13T13:41:20Z
OS/Arch:      linux/amd64


### What is your environment & configuration?

I have this in the static config of Traefik
```yaml
providers:
  consulCatalog:
    prefix: traefik
    exposedByDefault: False
    connectAware: True
    connectByDefault: True
[...]
```
The entrypoint is configured like this
```yaml
entryPoints:
  mariadb:
    address: ":3306"
    proxyProtocol:
      trustedIPs:
        - 10.99.9.1
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 4
```

**Comment by dani** [comment]
Forgot to add : even with rc1, both the router and the service appear in Traefik dashboard as if everything were OK. Only the routing is broken

**Comment by dani** [comment]
mmm, after some more debugging, the problem is not with the service mesh support. But with proxyProtocol.trustedIPs on the entrypoint (I set this as 10.99.9.1 is my HAProxy which can expose services from the outside, working as an L4 proxy, so I need the proxyProtocol support to get the real client IP).

Not sure what's special about it, because the same proxyProtocol.trustedIPs is also used on other entrypoints (like one for a postgres service, and several http services), but removing it makes my mariadb instance accessible again

**Comment by rtribotte** [comment]
Hello @dani,

Thanks for reporting this!

We are unsure about a few things to be able to reproduce the issue:
> mmm, after some more debugging, the problem is not with the service mesh support. But with proxyProtocol.trustedIPs on the entrypoint (I set this as 10.99.9.1 is my HAProxy which can expose services from the outside, working as an L4 proxy, so I need the proxyProtocol support to get the real client IP).

When you are trying to connect to MariaDB is this through HAPRoxy?

> Not sure what's special about it, because the same proxyProtocol.trustedIPs is also used on other entrypoints (like one for a postgres service, and several http services), but removing it makes my mariadb instance accessible again

Did you remove the whole proxyProtocol configuration or just the `trustedIPs` configuration?

Can you please share the full DEBUG logs of Traefik when reproducing the problem?

**Comment by dani** [comment]
Ok, so here are some more info
- I encounter the issue when I connect directly, not using HAProxy (this particular service is not yet exposed by HAProxy, I just configure all my entrypoints like this so if I need to expose it, everything is ready)
- trustedIPs is the only attribute under proxyProtocol, so I have to remove the whole proxyProtocol node (as specifying an empty node as proxyProtocol: {} is invalid and Traefik fails to start)
- The only logs in DEBUG are (filtered, as this Traefik handles quite a lot of other, unrelated trafic)
```
2024-02-19T16:15:25+01:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:85 > Accepting IP 192.168.7.32 middlewareName=ip-trusted@file middlewareType=IPAllowLister
2024-02-19T16:15:26+01:00 DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41 > Handling TCP connection address=10.99.9.11:23953 remoteAddr=10.99.20.2:35772
2024-02-19T16:15:31+01:00 DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:452 > IP 10.99.20.2 is not in trusted IPs list, ignoring ProxyProtocol Headers and bypass connection entryPointName=mariadb
```

Note : 
- I did set a IPAllowList middleware on this service (omitted when I opened the issue because it's not relevant, the issue is the same with or without this middleware)
- 10.99.20.2 is the IP of the client trying to connect (and getting a timeout)
- 10.99.9.11:23953 is the correct address for the backend service (IP:port of the envoy proxy in the service mesh)

**Comment by rtribotte** [comment]
Thanks for your feedback!

We are able to reproduce the problem, configuring the [`readTimout`](https://doc.traefik.io/traefik/v3.0/routing/entrypoints/#respondingtimeouts) option on the entryPoint should do the trick.

Stay tuned, we are working on a fix.

**Comment by rtribotte** [comment]
Hello @dani,

Could you please confirm that the bug is fixed with the latest version of v3?

**Comment by dani** [comment]
I still need to omit proxyProtocol.trustedIPs for my mariadb entrypoint. Else, I'm still having a timeout when a client tries to connect (now running Traefik 3.1.0)
