### ISSUE TITLE
High CPU usage on traefik v2 compared to v1

### ISSUE THREAD

**Issue by alkar** [traefik/traefik#6954]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Migrating a chunk of traffic from traefik v1.7.14 to v2.2.0, we noticed that the
latter uses a lot more CPU, so we decided to investigate a little bit deeper.

### Output of `traefik version`: (_What version of Traefik are you using?_)

See above.

#### The testing setup

In order to try to understand the issue here, we used the following setup:

Two traefik kubernetes Deployments of 9 replicas, each with the following
resource configuration:

```yaml
resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 250m
    memory: 250Mi
```

Both traefik Deployments are behind a NodePort type Service, behind an AWS
Network Load Balancer.

The cluster where they are hosted is generally not doing much besides log and
metrics collection. It does not receive external traffic (or at least the
amount of traffic it may occassionally receive is negligible) and is not
running an resource-hungry processes. Essentially, traefik should be able to
reach the limits of its resource allocation.

The traffic we used on these two traefik Deployments was mirrored from the
environment where we initially noticed the issue.

#### Traefik configuration

traefik v1:

```yaml
args:
  - --debug
  - --api
  - --api.entryPoint=system
  - --ping
  - --ping.entryPoint=system
  - --metrics
  - --metrics.prometheus
  - --metrics.prometheus.entryPoint=system
  - --logLevel=ERROR
  - --kubernetes
  - --kubernetes.labelselector=kubernetes.io/ingress.class=traefik-public-tls
  - --entryPoints=Name:http Address::80
  - --entryPoints=Name:https Address::443 TLS
  - --entryPoints=Name:system Address::8080
  - --defaultentrypoints=http,https
```

traefik v2:

```yaml
args:
  - --api.insecure=true
  - --api.debug=true
  - --ping
  - --metrics.prometheus
  - --log.level=ERROR
  - --providers.kubernetescrd.labelselector=kubernetes.io/ingress.class=traefik-public-v2
  - --providers.kubernetesingress.labelselector=kubernetes.io/ingress.class=traefik-public-v2
  - --entryPoints.web.address=:80
  - --entryPoints.web-secure.address=:443
  - --entryPoints.web-secure.http.tls=true
  - --entryPoints.traefik.address=:8080
```

### What did you expect to see?

We expected to see comparable resource usage between the v1 and v2 traefik
Deployments.

### What did you see instead?

Instead, we noticed that traefik v2 was using _considerably_ more CPU, compared
to v1.

Additionally, while tailing the logs of the traffic generating processes, we
noticed that using the v2 Ingresses resulted in noticably more 504 responses
when the system was stressed and that v2 traefiks were more likely to restart as
a result. However, this could have been due to the increased CPU usage,
throttling from docker etc.

For comparison, see the following graphs and profiles:
(graphs show the `sum(rate(container_cpu_usage_seconds_total))` of all traefik containers)

- http:
  <img width="1587" alt="v1_vs_v2_http" src="https://user-images.githubusercontent.com/898156/85397004-b198a600-b54a-11ea-98d2-a2ace46af47b.png">
  - [profile_v1_http.gz](https://github.com/containous/traefik/files/4819240/profile_v1_http.gz)
  - [profile_v2_http.gz](https://github.com/containous/traefik/files/4819243/profile_v2_http.gz)

- https (rsa):
  <img width="1607" alt="v2_vs_v1" src="https://user-images.githubusercontent.com/898156/85397085-dab93680-b54a-11ea-9f41-4498e3779f82.png">
  - [profile_v1_https.gz](https://github.com/containous/traefik/files/4819241/profile_v1_https.gz)
  - [profile_v2_https.gz](https://github.com/containous/traefik/files/4819244/profile_v2_https.gz)

- https (rsa vs ecdsa):
   Using an ECDSA certificate past the dip at 14:15 doesn't seem to have much of an effect:
   <img width="1601" alt="v2_rsa_vs_ecdsa" src="https://user-images.githubusercontent.com/898156/85415272-0812de00-b565-11ea-84e2-20a268d0d785.png">
  - [profile_v2_https_rsa.gz](https://github.com/containous/traefik/files/4819968/profile_v2_https_rsa.gz)
  - [profile_v2_https_ecdsa.gz](https://github.com/containous/traefik/files/4819967/profile_v2_https_ecdsa.gz)

**Comment by TheSpad** [comment]
I've been seeing this as well with v2.2.0, to the point that the container flattens the host within 5 minutes of exposing it to the internet and it starts getting even tiny amounts of "real" traffic.

**Comment by kallisti5** [comment]
We went back to v1.x   The design changes in v2.x *SUCK*, paired with reduced performance.
Traefik used to be the best ingress controller, but they really lost their way :-(

**Comment by JensErat** [comment]
We also observed a massive increase in CPU load when going from traefik 2.1.6 to 2.2.1 or 2.2.7. CPU usage increased by a factor of ~5. We're running a kind of special traefik instance here, which handles a large number of plain TCP connections with mTLS (configured through Kubernetes SD with `ingressroutetcps` and `tlsoptions`. We downgraded to 2.1.x again.

![image](https://user-images.githubusercontent.com/628441/88192065-669eab00-cc3c-11ea-8f08-1c4d48527cc3.png)

- - - 

Jens Erat <jens.erat@daimler.com>, Daimler TSS GmbH  
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by kolaente** [comment]
I'm also hitting this with a plain docker-compose installation. I observed it is sitting idle with basically no cpu being used until I start a request to a site which sits behind traefik. That request times out and the cpu usage goes up to the point where it clogs the whole system - all used up by traefik. To me, this sounds like traefik is running into some kind of infinite loop from which it does not recover.

**Comment by kolaente** [comment]
I collected some metrics about this, maybe someone can make sense of them:

The obvious spike in cpu usage:

![image](https://user-images.githubusercontent.com/13721712/95500839-bc673180-09a7-11eb-8b3d-bc4120b43be7.png)

![image](https://user-images.githubusercontent.com/13721712/95500890-d1dc5b80-09a7-11eb-92e8-2b0c748ecb5b.png)

![image](https://user-images.githubusercontent.com/13721712/95500936-e02a7780-09a7-11eb-8dbb-d227ddcd128b.png)

However, memory didn't went up:

![image](https://user-images.githubusercontent.com/13721712/95500873-cab54d80-09a7-11eb-9a98-aa485cc6d37b.png)

There were quite a lot of interrupts:

![image](https://user-images.githubusercontent.com/13721712/95500980-f2a4b100-09a7-11eb-9cb5-cf79e81d3df6.png)

And way more network traffic - I can't say if that was docker-internal or external:

![image](https://user-images.githubusercontent.com/13721712/95501075-0fd97f80-09a8-11eb-9496-92e05e470e0f.png)
![image](https://user-images.githubusercontent.com/13721712/95501082-12d47000-09a8-11eb-91ba-f27452ae737d.png)
![image](https://user-images.githubusercontent.com/13721712/95501093-149e3380-09a8-11eb-88a3-e37777f12b88.png)

Traefik latency also went up: 

![image](https://user-images.githubusercontent.com/13721712/95501181-326b9880-09a8-11eb-853e-4515d5894284.png)

I'm not sure if that's because traefik was clogging the cpu or other reasons.

Open connections didn't increase - that could also be an error in the logs collected since the system was kept busy by traefik at the time:

![image](https://user-images.githubusercontent.com/13721712/95501320-6777eb00-09a8-11eb-977a-c89468431b8c.png)

But the usage of sockets increased over time - this correlates with the usage of more network resources despite not many requests served in that period:
![image](https://user-images.githubusercontent.com/13721712/95501420-90987b80-09a8-11eb-8e18-b4055b6bf551.png)

**Comment by kolaente** [comment]
Now here's the weird thing: I rebooted the server and now it seems work again. This sounds like a memory leak which takes a bit of time to "leak", but that would show up as increased memory usage I think.

**Comment by povils** [comment]
Hey, I observer the exact issues with CPU using 2.2.0 version. The only fix we could do is to recreate the pods.

**Comment by pacifier007** [comment]
I was experiencing the same issue on a fresh Docker version 20.10.2 on Ubuntu 20.04LTS using the official 2.3 traefik image using docker-compose. A single website visitor would drive traefik to take upto 100% CPU. Countless hours of debugging and removing configs, nothing helped. What fixed was downgrading to v2.1 docker image (image: traefik:2.1) and rebuilding it all. 

I don't have the time or energy right now to go into details, but for someone experiencing the same issue, might be worth a shot.

**Comment by lowercase00** [comment]
Same thing with v2.2 running on EC2 in Docker Swarm mode. One of the managers crashes apparently from high CPU load, and takes quite a while to come back. Tried recreating everything, upgrading to `latest` and downgrading to `v2.1`, nothing helps.

**Comment by dtomcej** [comment]
Hello @lowercase00, do you think it would be possible to try enabling the debug mode, and providing us with a CPU pprof trace?

https://doc.traefik.io/traefik/operations/api/#debug

This would allow us to further debug what the CPU is doing during this period.

Thanks!

**Comment by lowercase00** [comment]
@dtomcej sure, be happy to. I will have to make a bit of research on how to save the CPU trace, but I'll get back to you. If you have any suggestions, please let me know I'll try to implement them right away.

**Comment by lowercase00** [comment]
@dtomcej so I've done a bit of digging, and seems that the problem is an inifite loop with the message `msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL"`. This happens when I go to a route that seems to be misconfigured (indeed I didn't get things right yet). So probably a very different case than what others have reported in this specific issue. This is my latest test with v2.1, but same behaviour in 2.2 and latest.


<details>
  <summary>Traefik Setup</summary>
*I just added the resource limits (there wasn't any before)

```
version: '3.3'

services:

  traefik:
    image: traefik:2.1
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.rule=Host(`api.example.com`)
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.http.services.traefik-public.loadbalancer.server.port=80
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=email@email.com
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --api.insecure=true
      - --api.dashboard=true
      - --accesslog
      - --log.level=debug
    networks:
      - traefik-public

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true

```
</details>


<details>
  <summary>Container Setup</summary>
What I was trying to achieve was: when you hit `api.example.com/flower` traefik would redirect the request to service named `flower`, that is exposed on port 8888. Obviously that didn't work out.

```
version: "3.7"

services:

  whoami:
    image: containous/whoami
    networks:
      - traefik-public
      - default    
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.whoami.rule=Host(`api.example.com`) && Path(`/whoami`)
        - traefik.http.services.whoami.loadbalancer.server.port=5555

  flask:
    image: example/example
    restart: always
    networks:
      - traefik-public
      - default    
    environment:
      FLASK_DEBUG: 1
    env_file:
      - .env
    ports:
      - 3333:8080      
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.flask.rule=Host(`api.example.com`)
        - traefik.http.services.flask.loadbalancer.server.port=3333

  flower:  
    image: mher/flower
    networks:
      - traefik-public
      - default
    env_file:
      - .env    
    ports:  
      - 8888:8888 
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.flower.rule=Host(`api.example.com`) && Path(`/flower`)
        - traefik.http.services.flower.loadbalancer.server.port=8888
```
</details>

<details>
<summary>The logs</summary>
As soon as I hit `/flower` I get thousands of log messages like this, than everything breaks, memory hits 100%,  and I can't even see the CPU evolution anymore since I'm kicked out of SSH and the server crashes completely.

```
traefik_traefik.1.wivss1yy13gp@ds1
time="2021-01-21T01:27:09Z"
level=debug
msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL"
ForwardURL="http://10.0.1.5:80"
Request="
{
    "Method":"GET\",\"URL\":
        {
            \"Scheme\":\"\",\"Opaque\":\"\",
            \"User\":null,
            \"Host\":\"\",
            \"Path\":\"/flower/\",
            \"RawPath\":\"\",
            \"ForceQuery\":false,
            \"RawQuery\":\"\",
            \"Fragment\":\"\"
        },
    \"Proto\":\"HTTP/1.1\",
    \"ProtoMajor\":1,
    \"ProtoMinor\":1,
    \"Header\":
        {
            \"Accept\":
                [
                    \"text/html,
                    application/xhtml+xml,
                    application/xml;q=0.9,
                    image/avif,
                    image/webp,
                    image/apng,
                    */*;q=0.8,
                    application/signed-exchange;
                    v=b3;q=0.9\"
                ],
            \"Accept-Encoding\": [ \"gzip, deflate\"],
            \"Accept-Language\":  [ \"en-US,en;q=0.9\"],
            \"Sec-Gpc\":[\"1\"],
            \"Upgrade-Insecure-Requests\":[\"1\"],
            \"User-Agent\":[\"Mozilla/5.0(Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36\"],
            \"X-Forwarded-Host\":[\"api.example.com\"],
            \"X-Forwarded-Port\":[\"80\"],
            \"X-Forwarded-Proto\":[\"http\"],
            \"X-Forwarded-Server\":[\"1f31b0bc2622\"],
            \"X-Real-Ip\":[\"10.0.1.5\"]},
            \"ContentLength\":0,
            \"TransferEncoding\":null,
            \"Host\":\"api.example.com\",
            \"Form\":null,
            \"PostForm\":null,
            \"MultipartForm\":null,
            \"Trailer\":null,
            \"RemoteAddr\":\"10.0.1.5:34164\",
            \"RequestURI\":\"/flower/\",
            \"TLS\":null
        }"
}
```
</details>

**Comment by kolaente** [comment]
I can confirm I'm seeing the same messages about roundrobin in the logs (with debug enabled).

To me, this just looks like the server is getting a lot of requests but at the same time there's 1-5 request log messages like that every 5 seconds so not something I'd consider high usage. Or at least not something that should cause traefik to use 180% CPU.

**Comment by kolaente** [comment]
I've enabled the debug api endpoints as per the suggestion from @dtomcej and here's everything: [traefik-debug.zip](https://github.com/traefik/traefik/files/5862037/traefik-debug.zip)

The profile looks like there something wrong somewhere, but I'm not quite sure why that is the case:

![profile001](https://user-images.githubusercontent.com/13721712/105628216-f3b8fb80-5e3b-11eb-901c-b353e0440e5d.png)

**Comment by escoand** [comment]
Maybe it's not related but when working with the Nextcloud web interface (official nextcloud image), I can see from time to time many many apache processes get created. Not sure if this is a result of the graph above or the reason. Additionally you can also see in the screenshot below the massive cpu time used by traefik compared to mysqld.
![Bildschirmfoto von 2021-01-25 15-30-04](https://user-images.githubusercontent.com/428567/105719676-dca10900-5f22-11eb-9c06-b0488efcb5a5.png)

**Comment by ldez** [comment]
@kolaente I think your problem is related to #7845

**Comment by kolaente** [comment]
@ldez Even If I had the same problem before 2.4.0?

**Comment by ldez** [comment]
> Even If I had the same problem before 2.4.0?

no only with 2.4.0 and v2.4.1

**Comment by kolaente** [comment]
> no only with 2.4.0 and v2.4.

Hmm then it probably wasn't that - I'll ping here if it happens with 2.4.2 again

**Comment by ldez** [comment]
@kolaente I spend some time analyzing your data from `traefik-debug.zip` bug the data seems weird.

If you still have the issue could you:
- start traefik with the API debug mode https://doc.traefik.io/traefik/operations/api/#debug
- execute the following commands:
```bash
curl -o profile.pprof <traefik_api_url>/debug/pprof/profile    # CPU (takes 30 seconds to return)
curl -o heap.pprof <traefik_api_url>/debug/pprof/heap    
curl -o block.pprof <traefik_api_url>/debug/pprof/block    
curl -o mutex.pprof <traefik_api_url>/debug/pprof/mutex
curl -o goroutine.pprof <traefik_api_url>/debug/pprof/goroutine
curl -o trace.pprof <traefik_api_url>/debug/pprof/trace?seconds=5    # the seconds parameter is needed
```
- provide your configurations (static and dynamic)
- create a minimal reproducible (at least for you) example

Anyone with a similar problem can do the same thing and post the result (in an archive)

**Comment by kolaente** [comment]
Here's the debug log from right now where the server works without issues (I'm not sure if that's actually helpful): [traefik-debug.zip](https://github.com/traefik/traefik/files/5928574/traefik-debug.zip)

The big problem here is it happens sparingly from time to time which makes it a lot harder to reproduce. I'll try to come up with a minimal example, but I'm not sure if I'll be able to.

Traefik Version: 2.4.2

Config: [traefik-config.zip](https://github.com/traefik/traefik/files/5928669/traefik-config.zip)

All services are run with docker and have a config somewhat similar to this:
```
version: '2'
services:
  web:
    image: image
    build: build/
    volumes:
    - /var/wobsites/website/html:/var/www/html
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.life.rule=Host(`example.com`, `www.example.com`)"
      - "traefik.http.routers.life.entrypoints=https"
      - "traefik.http.routers.life.tls.certResolver=basic"
      - "traefik.http.routers.life.middlewares=www-redirect@file"
    networks:
      - web
      - default
    restart: unless-stopped

networks:
  web:
    external: true
```

**Comment by 3nprob** [comment]
Similar experience here (very high CPU load and context switching) on 2.3.7 through 2.4.2.

Unfortunately we're relying on recently introduced configuration, so can not roll back to test 2.1.9.

One thing I note is that two services in particular (that were not having this behavor in earlier versions) causing this. Both run tcp+udp on the same port with 20~60 simultaneous connections each. Increasing the number of peers on these services has a corresponding increase in CPU load + context switches the latter of whih I guess is expected).

**Comment by kolaente** [comment]
@ldez Just happended again, here's the pprof files from while it was hanging: [traefik-debug.zip](https://github.com/traefik/traefik/files/5973797/traefik-debug.zip)

**Comment by snwfdhmp** [comment]
Any update oon this ?

**Comment by MrOwen** [comment]
I'm also ran into this problem on the latest 2.4.x Traefik (around the same time this issue was opened) and reverting to 2.3.x branch got rid of the issue as others here have suggested. If @kolaente's debug dump isn't enough, I can certainly try to reproduce and send one over as well. I'm on a standard k3s cluster with 3 nodes, metallb, and flannel as CNI.

**Comment by lyda** [comment]
We also saw this issue on a small cluster.

**Comment by snwfdhmp** [comment]
@ldez @juliens I know you have done a lot for this project and I request your opinion on this topic.

I know this method is bad but keeping CPU usage issues open after 1 year of quality documentation seems not good either, specially when the project is claimed to be production-ready and is widely used.

Thanks a lot in advance if you can help here. I know open source is not easy.

**Comment by brunocascio** [comment]
@MrOwen reverting to 2.3 does work? Are you using TRAEFIK_PING? Because I notice would be related to that feature

**Comment by Xstoudi** [comment]
Any update on this? I experience the same thing.

**Comment by Ruppsn** [comment]
We have the same Problem since we moved to 2.4.x branch. 

CPU is always between 90-100%.

Changed to 2.3 back -> Problem disapears.

**Comment by Xstoudi** [comment]
Right now on traefik:latest image, the issue is fixed for. I was basically in debug and noticed it when my HDD was full of 2 big TB of logs.

**Comment by everyx** [comment]
same problem here with `traefik:v2.6.1`. It will occurs once every two months, and take the system to freeze.

**Comment by ddtmachado** [comment]
@everyx Traefik 2.6.1 was released 40 days ago so I guess it can't be happening every 2 months, unless you wanted to say you still experienced a hang or freeze that can be directly related to high CPU spikes after upgrading to it?

If so would you be able to send us a profile, instructions [here](https://github.com/traefik/traefik/issues/6954#issuecomment-773572813) in order to compare the stack with what we have on other reports? Thanks

**Comment by everyx** [comment]
> @everyx Traefik 2.6.1 was released 40 days ago so I guess it can't be happening every 2 months, unless you wanted to say you still experienced a hang or freeze that can be directly related to high CPU spikes after upgrading to it?
> 
> If so would you be able to send us a profile, instructions [here](https://github.com/traefik/traefik/issues/6954#issuecomment-773572813) in order to compare the stack with what we have on other reports? Thanks

@ddtmachado  This happened again today and I found some kernel error, so is this a system problem? is it caused by traefik?
```shell
Apr 29 01:20:15 xxxx kernel: TCP: out of memory -- consider tuning tcp_mem
```

**Comment by ddtmachado** [comment]
@everyx Probably not a system problem and could be caused by Traefik as it tried to use more memory than is allowed by the system configuration for the TCP stack.

You can check current parameters with: 
```bash
cat /proc/sys/net/ipv4/tcp_mem
```

This is the meaning of the returned values, according to the kernel man pages:
```
low    TCP doesn't regulate its memory allocation when the
                     number of pages it has allocated globally is below
                     this number.

              pressure
                     When the amount of memory allocated by TCP exceeds
                     this number of pages, TCP moderates its memory
                     consumption.  This memory pressure state is exited
                     once the number of pages allocated falls below the
                     low mark.

              high   The maximum number of pages, globally, that TCP
                     will allocate.  This value overrides any other
                     limits imposed by the kernel.
```

Increasing those limits might prevent your Traefik instance from being OOM'ed by the system so often, just buying more time as if there is a leak it will still reach the new limit at some point.

**Comment by everyx** [comment]
> Probably not a system problem and could be caused by Traefik as it tried to use more memory than is allowed by the system configuration for the TCP stack.

@ddtmachado I think so, since this only occurs on the host where I run traefik, and recurs every once in a while. Is this related to my use of docker swarm to deploy traefik?

I have increase some properties limit about `tcp_men` from:

```ini
net.core.netdev_max_backlog = 1000
net.core.rmem_max = 212992
net.core.wmem_max = 212992
net.ipv4.tcp_max_syn_backlog = 256
net.ipv4.tcp_rmem = 4096        87380   6291456
net.ipv4.tcp_wmem = 4096        20480   4194304
```

to below

```ini
net.core.netdev_max_backlog=30000
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 87380 67108864
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by 3nprob** [comment]
I do find it peculiar to auto-close without notice and prefer opening a new issue over reusing the existing one...
Either way, this still seems to be an issue, reopened as #9139

**Comment by ddtmachado** [comment]
@3nprob sorry for the inconvenience, this is really an auto action for issues without activity and labeled as waiting for feedback, which was not correct on this one :)

I'm reopening it and closing the new one as duplicate, better to keep everything here.

By the way, if you're still experiencing this on the latest version please with us your configuration and CPU profile if possible.

**Comment by 3nprob** [comment]
@ddtmachado thanks for attending it promptly.

We do still see it on 2.7.0, will see if we can get a profile in.

(BTW for the future maybe it's worth reformulating the message in the bot if kept around as its currently instructing us to open duplicates which you seem to agree is not ideal for tracking issues over time)

**Comment by everyx** [comment]
> @ddtmachado thanks for attending it promptly.
> 
> We do still see it on 2.7.0, will see if we can get a profile in.
> 
> (BTW for the future maybe it's worth reformulating the message in the bot if kept around as its currently instructing participants to open duplicates which you seem to agree is not ideal for tracking issues over time. What seems to work best for projects who declare issue-bankruptcy is the bot commenting "I'm going to auto-close this in 30 days unless further activity on the issue", giving a reasonable time-window for participants to keep it open by bumping it)

Yes, I also ran into this problem again with v2.7.0, my machine is configured with `1vcpu/2G ram` and `2vcpu/4G ram`

**Comment by everyx** [comment]
Problem still exists in Traefik 2.9.4 with digitalocean's `2vcpu(shared)/4g ram` droplet.

**Comment by jjaarddev** [comment]
I also wondering that high resource usage by Traefik, the interesting experiment what I did using just streaming 4K video - I compared usage when using binary installation and Docker, and results are that when used in Docker is uses about 25% of CPU, while binary installation - just about 5%

**Comment by mohanish2504** [comment]
> I also wondering that high resource usage by Traefik, the interesting experiment what I did using just streaming 4K video - I compared usage when using binary installation and Docker, and results are that when used in Docker is uses about 25% of CPU, while binary installation - just about 5%

@jjaarddev can you please guide me how to use binary with docker-compose file. I was able to isntall binary but not able to figure how to link it with docker.

**Comment by zthxxx** [comment]
Same problem exists in Traefik v2.10.1 with docker.

**Comment by bevinhex** [comment]
Same here with v2.10.1 in docker using network=host, debian 11, 2 cpu , 4gb ram, on OVH VPS

**Comment by nefarius** [comment]
Anybody has a lead on this? Still happens fairly regularly, within 2 hours, sometimes more, uses all cores and slows down traffic for maybe a minute until it recovers from whatever it is doing.

**Comment by markverg** [comment]
This issue exists for more than 37 months now, it keep getting found and new replies keep coming but I don't think anyone cares enough too fix it. Afraid we need to wait for V3, see if that has the issue as well and start over again.

**Comment by ldez** [comment]
> I don't think anyone cares enough too fix it

This is not true: we already have fixed several elements related to CPU consumption and performance.

The problems here are the issue itself, and being able to have something to diagnose.

We spent a lot of time analyzing pproof reports, and we have fixed what we found.
But it's a complex and time-consuming task.

The original topic was the difference between v1 and v2 (at some point it's expected), but comments drifted on the subject of CPU consumption in general, and with messages like "I have the same problem" but without information to reproduce and diagnose or being able to know if the problems are related.

This issue is now impossible to fix.
I think we should close this issue, not because the problems expressed inside the issue are fixed, but just because this issue contains multiple things.
And suggest opening new problems for each person.

**Comment by ldez** [comment]
You can follow my previous comment: https://github.com/traefik/traefik/issues/6954#issuecomment-773572813

**Comment by dustsucker** [comment]
I have the same Problem of really high CPU usage I have a VM with 1 GB of memory and 2 cores and traefik has about 5000 services, routers, middlewares loaded trough Redis and htop reports traefik taking about one full core of load. Load average in htop of 1.6. Why is traefik taking so much CPU in idle? I mean, the only thing it has to do right now is hold the config there are no requests on this dev environment.

**Comment by ldez** [comment]
> I still think the core root cause of this one is the addition of all the middleware layer stuff in 2.x really increased the resource requirements to run Traefik, and cut down overall performance.

The middleware was already inside v1, just the name was different.

**Comment by ldez** [comment]
After discussing with the team: this issue doesn't let us handle the topic well.

We will close this issue, not because the problems expressed inside the issue are fixed, but just because this issue contains multiple topics.

We suggest opening new issues, one per person, with the following information:

- start traefik with the API debug mode https://doc.traefik.io/traefik/operations/api/#debug
- execute the following commands (and provide the output in an archive):
```bash
curl -o profile.pprof <traefik_api_url>/debug/pprof/profile    # CPU (takes 30 seconds to return)
curl -o heap.pprof <traefik_api_url>/debug/pprof/heap    
curl -o block.pprof <traefik_api_url>/debug/pprof/block    
curl -o mutex.pprof <traefik_api_url>/debug/pprof/mutex
curl -o goroutine.pprof <traefik_api_url>/debug/pprof/goroutine
curl -o trace.pprof <traefik_api_url>/debug/pprof/trace?seconds=5    # the seconds parameter is needed
```
- provide your configurations (static and dynamic)
- provide the exact traefik version
- logs from the start of traefik
- create a minimal reproducible (at least for you) example

We hope this will help us to help you.
