### ISSUE TITLE
latest traefik 2.4.1 causes 100% cpu usage

### ISSUE THREAD

**Issue by wiserain** [traefik/traefik#7845]
### What did you do?

Simply did pull and up for the latest docker image from v2.4.0

### What did you expect to see?

Normal conditions

### What did you see instead?

100% cpu usage

![PicPick_Capture_20210202_001](https://user-images.githubusercontent.com/20354654/106524832-728df280-6526-11eb-8e17-7017f1405f2d.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

docker image with tag traefik:latest
```
Version:      2.4.1
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-01T16:28:12Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Three instances (one local VM and two VPS) are the same. They are all based on ubuntu 20.04.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Nothing special, but might be helpful it stops logging after `msg="Anonymous stats sent to ... `

Everything is okay after downgrade to v2.4.0.

**Comment by ldez** [comment]
Hello,

Could you provide more information about your configuration? And a minimal reproducible example?

**Comment by wiserain** [comment]
I found no more high cpu usage after removing a dynamic toml configuration file from dir specified in command arg `--providers.file.directory`. I am narrowing down which part of `conf` is the problem.

**Comment by mpatton125** [comment]
Just a comment to say +1 - also experiencing 100% CPU with new docker image for 2.4.1.
No real triage yet (I am at work, and this is at home) but it's not just the OP.

**Comment by ldez** [comment]
@mpatton125 Could you provide more information about your configuration and your logs? And a minimal reproducible example?

**Comment by wiserain** [comment]
I got to know one routing rule for a specific app is loaded then it starts consuming cpu.

`docker-compose.yml` for running traefik.
```yaml
version: '3.7'

services:

  traefik:
    container_name: traefik
    image: traefik:2.4.1
    restart: always
    healthcheck:
      test: traefik healthcheck --ping
    logging:
      driver: json-file
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --ping=true
      - --api=true
      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.leresolver.acme.email=${TRF_LE_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --pilot.token=${TRF_PILOT_TOKEN}
    network_mode: host
    ports:
      # https://www.reddit.com/r/docker/comments/c1wrep/traefik_reverse_proxy_question_docker_overlay/
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_ROOT}/traefik/acme.json:/acme.json
      - ${DOCKER_ROOT}/traefik/traefik.log:/traefik.log
      - ${DOCKER_ROOT}/traefik/rules:/rules
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`sub.${TRF_DOMAIN}`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik-rtr.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=leresolver"
      # Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=mid-basicauth@file,traefik-stripprefix"
      - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/traefik"
      # Services - API
      # https://github.com/containous/traefik/issues/5732
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=1337"
      - "traefik.http.routers.traefik-rtr.service=api@internal"
```

`dynamic-conf.toml` for routing the app.

```toml
# app
[http.routers.app-rtr]
    rule = "Host(`app.mydomain.com`)"
    service = "app-svc"
    entryPoints = ["https"]
[http.routers.app-rtr.tls]
    certResolver = "leresolver"
[http.services.app-svc.loadbalancer]
    [[http.services.app-svc.loadbalancer.servers]]
        url = "http://192.168.1.99:9999"


[tls.options.default]
    minVersion = "VersionTLS12"
    curvePreferences = ["secp521r1", "secp384r1"]
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]
    sniStrict = true 
```

I cannot tell details about the app because it not opened. But it is a simple python web-app using flask and socketio. I am highly suspicious on below log lines which is keep repeating every seconds.

```
traefik    | time="2021-02-02T13:25:09+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://192.168.1.99:9999" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_KlO\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_KlO\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:10+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_KlO\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_KlO\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:10+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:10+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://192.168.1.99:9999" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:11+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_K_4\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:11+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:11+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}" ForwardURL="http://192.168.1.99:9999"
traefik    | time="2021-02-02T13:25:12+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_LEt\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:12+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_LUa\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_LUa\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
traefik    | time="2021-02-02T13:25:12+09:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://192.168.1.99:9999" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/socket.io/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"EIO=3\\u0026transport=polling\\u0026t=NTW_LUa\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cookie\":[\"io=f930a2d40a7849718f33b94d6f809235; _ga=GA1.2.1653626623.1599423916; __gads=ID=d339e1e6e35f9a60-22b67ec457c30007:T=1599423931:RT=1599423931:S=ALNI_MZ6IJLdIbVNNnIJDdasvgmvWzIL7g; remember_token=thisisredactedmyid|7057a38a6eb10df48a853c41b14cd3525b0ad533a61430e366acc481bb8b7bc96f2997994d2afac3f322295845969bf37fd3b711a862ff9caa37cdaba552fcf1; io=a14af99618ac4c0a8cc0e437f9ce8c38; session=.eJwljkuKwzAQRK8ieh0G_dwt-xSzH0JoqVuxwTMOls0sQu4eQVZFfSjeE2515TZrg-nnCeboAr_aGt8VLvC9Kjc163Y3y585NsOl9NIc89LMo2--4Pq6XvrJrm2G6dhP7W4RmCBRSZVQqldbQ2BnNVASQq6JRkQXOapDRE8cc6RAVSLZKINIcaqhWF9lVJZMQ8zIQuyEclYZkqB1HHkgz-MYQkE72uqtaM3Fh55S6fi3s-n-oSnzuf5vG7zezedJ3Q.YBjRtQ.T2Y1FBE9bFVRLIymAzSf0AmbGzU\"],\"Referer\":[\"https://app.mydomain.com/system/home\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0\"],\"X-Forwarded-Host\":[\"app.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"xpenology\"],\"X-Real-Ip\":[\"192.168.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.1:6810\",\"RequestURI\":\"/socket.io/?EIO=3\\u0026transport=polling\\u0026t=NTW_LUa\\u0026sid=a14af99618ac4c0a8cc0e437f9ce8c38\",\"TLS\":null}"
```

**Comment by mpatton125** [comment]
Even when _just_ running Traefik v2.4.1 by itself, no actual running services or other containers etc - the problem still comes up after around 10 minutes or so.  The CPU utilisation creeps up to 100% on 1 core and then another core, and another core etc.

Nothing apart from access logs in my DEBUG logs, after initial launch.

traefik.yml and dynamic.yml attached.

[traefik.yml.txt](https://github.com/traefik/traefik/files/5908889/traefik.yml.txt)
[dynamic.yml.txt](https://github.com/traefik/traefik/files/5908890/dynamic.yml.txt)

Compose.yml attached.

[compose.yml.txt](https://github.com/traefik/traefik/files/5908913/compose.yml.txt)

Hope there's something useful in there...

M.

**Comment by traefiker** [comment]
Closed by #7847.

**Comment by TheSpad** [comment]
I'm still seeing this behaviour with 2.4.2

**Comment by povils** [comment]
Why this one was closed?

**Comment by ldez** [comment]
Because the initial problem reported by the user was fixed.

**Comment by povils** [comment]
Ok thanks! I think i just wrongly went down to a rabbit hole regarding https://github.com/traefik/traefik/issues/6954 which is still a problem in 2.4.2
