### ISSUE TITLE
Possible memory leak, regexp instructions consuming a lot of memory

### ISSUE THREAD

**Issue by kungfukennyg** [traefik/traefik#8044]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
We run a single Traefik node in a Docker container (started via Nomad) on an AWS t3.medium EC2 instance hooked up to a `Consul` network, and our workflow involves creating many thousands of Nomad jobs that are made accessible to the wider internet via Traefik. Traefik works fine for this, but exhibits leaky behavior as it stays up longer, until it eventually kills the EC2 instance or gets restarted by Nomad.
![Screen Shot 2021-04-06 at 15 49 41](https://user-images.githubusercontent.com/6355483/114197918-d535ad00-9920-11eb-962b-4defc674b868.png)

We initially noticed this on Traefik v2.2.5, and upgraded to v.2.3.7 to see if that fixed the issue, but sadly it did not. 

### What did you expect to see?
Memory falling after Nomad jobs are completed and the applications are no longer accessible.

### What did you see instead?
Memory growing unbounded. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Environment variables:
```console
# env | grep TRAEFIK
TRAEFIK_METRICS_STATSD_ADDRESS=127.0.0.1:8125
TRAEFIK_PROVIDERS_CONSULCATALOG_EXPOSEDBYDEFAULT=false
TRAEFIK_LOG_LEVEL=INFO
TRAEFIK_ACCESSLOG=true
TRAEFIK_LOG_FORMAT=json
TRAEFIK_ACCESSLOG_FORMAT=json
TRAEFIK_ENTRYPOINTS_tcp_ADDRESS=:5672
TRAEFIK_METRICS_STATSD=true
TRAEFIK_PROVIDERS_CONSULCATALOG_ENDPOINT_SCHEME=http
TRAEFIK_ENTRYPOINTS_http_ADDRESS=:8080
TRAEFIK_PROVIDERS_CONSULCATALOG_ENDPOINT_ADDRESS=127.0.0.1:8500
TRAEFIK_API_DEBUG=true
TRAEFIK_API_INSECURE=true
TRAEFIK_API_DASHBOARD=true
TRAEFIK_ENTRYPOINTS_traefik_ADDRESS=:8081
TRAEFIK_PROVIDERS_CONSULCATALOG_PREFIX=traefik
TRAEFIK_LOG=true
```

We configure the Nomad jobs we access through Traefik with some middlewares as well. We define these for every job when we submit them to Nomad. 
```
"traefik.enable=true",
"traefik.http.routers.<app-id>.rule=PathPrefix(`/<app-id>/`",
"traefik.http.routers.<app-id>.middlewares=cloud-auth,<app-id>
    + (hasBasicAuth ? ",auth-" + <app-id> : ""),
"traefik.http.middlewares.<app-id>.stripprefix.prefixes=/"<app-id>/",
"traefik.http.middlewares.<app-id>.stripprefix.forceslash=false")
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I gathered this pprof data that shows the problem:
```console
sh-4.2$ go tool pprof http://localhost:8081/debug/pprof/heap
Fetching profile over HTTP from http://localhost:8081/debug/pprof/heap
Saved profile in /home/ssm-user/pprof/pprof.traefik.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz
File: traefik
Type: inuse_space
Time: Apr 9, 2021 at 2:44pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 190.30MB, 66.66% of 285.50MB total
Dropped 60 nodes (cum <= 1.43MB)
Showing top 10 nodes out of 146
      flat  flat%   sum%        cum   cum%
  102.76MB 35.99% 35.99%   102.76MB 35.99%  regexp/syntax.(*compiler).inst (inline)
   14.50MB  5.08% 41.07%    14.50MB  5.08%  github.com/traefik/traefik/v2/pkg/middlewares/auth.getUsers
      14MB  4.90% 45.98%       14MB  4.90%  github.com/traefik/traefik/v2/pkg/config/runtime.(*ServiceInfo).UpdateServerStatus
      12MB  4.20% 50.18%       12MB  4.20%  github.com/gorilla/mux.(*Router).NewRoute
   10.50MB  3.68% 53.86%    10.50MB  3.68%  regexp/syntax.(*parser).maybeConcat
       9MB  3.15% 57.01%        9MB  3.15%  github.com/traefik/traefik/v2/pkg/server/provider.MakeQualifiedName
       8MB  2.80% 59.82%   122.77MB 43.00%  regexp.compile
    6.53MB  2.29% 62.10%     6.53MB  2.29%  bufio.NewReaderSize
    6.50MB  2.28% 64.38%     6.50MB  2.28%  github.com/vulcand/oxy/utils.CopyURL
    6.50MB  2.28% 66.66%     6.50MB  2.28%  encoding/json.(*decodeState).literalStore
```

**Comment by jbdoumenjou** [comment]
Hi @kungfukennyg ,

Thanks for your interest in Traefik!
Could you test with the last available version?

**Comment by kungfukennyg** [comment]
My mistake, I thought we were on the latest version! I will do so and report back.

**Comment by kungfukennyg** [comment]
It looks like v2.4.8 has alleviated the constant memory climb, thanks!

**Comment by kungfukennyg** [comment]
I spoke too soon -- while v2.4.8 definitely helped with our memory climb, it did not totally alleviate the memory leak: 
<img width="1566" alt="Screen Shot 2021-04-14 at 10 34 46 AM" src="https://user-images.githubusercontent.com/6355483/114728450-19ec8a00-9d0d-11eb-9d8e-55dec06bd067.png">

```sh-4.2$ go tool pprof -nodefraction=0 http://localhost:8081/debug/pprof/heap
Fetching profile over HTTP from http://localhost:8081/debug/pprof/heap
Saved profile in /home/ssm-user/pprof/pprof.traefik.alloc_objects.alloc_space.inuse_objects.inuse_space.013.pb.gz
File: traefik
Type: inuse_space
Time: Apr 14, 2021 at 2:35pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 195.77MB, 79.15% of 247.33MB total
Showing top 10 nodes out of 185
      flat  flat%   sum%        cum   cum%
   78.20MB 31.62% 31.62%    78.20MB 31.62%  regexp/syntax.(*compiler).inst (inline)
   38.80MB 15.69% 47.30%    38.80MB 15.69%  bufio.NewReaderSize
   37.76MB 15.27% 62.57%    37.76MB 15.27%  bufio.NewWriterSize
       7MB  2.83% 65.40%        7MB  2.83%  github.com/gorilla/mux.(*Router).NewRoute
       7MB  2.83% 68.24%        7MB  2.83%  github.com/traefik/traefik/v2/pkg/config/runtime.(*ServiceInfo).UpdateServerStatus
       6MB  2.43% 70.66%        6MB  2.43%  github.com/traefik/traefik/v2/pkg/middlewares/auth.getUsers
       6MB  2.43% 73.09%        6MB  2.43%  encoding/json.(*decodeState).literalStore
       5MB  2.02% 75.11%        5MB  2.02%  regexp/syntax.(*parser).maybeConcat
       5MB  2.02% 77.13%    90.20MB 36.47%  regexp.compile
       5MB  2.02% 79.15%        5MB  2.02%  github.com/vulcand/oxy/roundrobin.New```

**Comment by kungfukennyg** [comment]
Some more pprof data, sitting at roughly 75% memory:

```Showing top 10 nodes out of 259
      flat  flat%   sum%        cum   cum%
  320.82MB 27.36% 27.36%   320.82MB 27.36%  regexp/syntax.(*compiler).inst (inline)
  192.02MB 16.38% 43.74%   192.02MB 16.38%  bufio.NewWriterSize
  188.17MB 16.05% 59.79%   188.17MB 16.05%  bufio.NewReaderSize
   38.51MB  3.28% 63.07%    38.51MB  3.28%  github.com/gorilla/mux.(*Router).NewRoute
   36.51MB  3.11% 66.19%    36.51MB  3.11%  github.com/traefik/traefik/v2/pkg/middlewares/auth.getUsers
   32.01MB  2.73% 68.91%    32.01MB  2.73%  github.com/traefik/traefik/v2/pkg/config/runtime.(*ServiceInfo).UpdateServerStatus
   29.51MB  2.52% 71.43%    29.51MB  2.52%  regexp/syntax.(*parser).maybeConcat
   24.50MB  2.09% 73.52%    24.50MB  2.09%  github.com/traefik/traefik/v2/pkg/server/provider.MakeQualifiedName
      20MB  1.71% 75.23%   376.83MB 32.14%  regexp.compile
   18.50MB  1.58% 76.81%    18.50MB  1.58%  encoding/json.(*decodeState).literalStore```
   
   
  
I'm curious if we're using Traefik wrong. We dynamically submit a router config with basic auth and other middlewares defined for every unique application run (I show an example of this in my first comment) we run, and we don't do anything to explicitly clear these. I could see memory creeping up if routers/middlewares are not meant to be submitted and/or are supposed to be removed when the application is closed.

**Comment by everflux** [comment]
This could be the same underlying issue as https://github.com/traefik/traefik/issues/7964 since both show high memory usage in the regexp part.

**Comment by kungfukennyg** [comment]
Is there anything else I can do to help diagnose/debug this issue?

**Comment by rtribotte** [comment]
Hello @kungfukennyg,

Thank you for what you have provided so far.
We don't see for now what could help us more to diagnose this issue, but we will for sure come back to you if we need more information.
To let you know, and as mentioned by @everflux, we are aware of that issue and have other memory consumption issues that we are looking into, but unfortunately with no concrete conclusions yet.
Obviously, this will need more investigation on our side in the near future.

**Comment by sarkistlt** [comment]
Any updates on this issue? Didn't want to create duplicate but I have exactly the same issue, also mentioned in the ticket #7964, tested on 2.3.* and now running 2.4.8, issue is still there, and leak goes up with the network traffic, in my case k8s kills deployment ones a week, and we are running production project with the proxy, so would be great to know if this will be fixed any time soon, or if there any workaround? 

Happy to help with debugging and provided additional information if needed.

Also for a record I'm running 2 separate projects on 2 separate clusters, both have ~same traffic, one runes on 2.3.2 and another one upgraded from 2.3.2 to 2.4.8 (but didn't fix the issue).

Main difference between 2 projects, second one with the issue heavily relies on regex due to the project requirements, and has one TCP endpoint vs first one mostly static endpoints and all http.

**Comment by cidrick** [comment]
Our team has recently attempted to upgrade from Traefik v1.7.20 to 2.4.8, and we immediately ran into memory issues. Even after tripling the memory limit on our Traefik Kubernetes deployment (8Gi to 24Gi), we're having Traefik pods OOMkilled in production very frequently - so much so that we're in the process of rolling back to v1 😞 

Our symptoms have been similar to this issue, as well as #7964. One thing to note is that we are _not_ actively using any Middleware for our ingress resources, in case that helps to narrow things down. We are using `HostRegexp` in a handful of our ingresses, and `pprof` seems to also point towards the regexp libraries being an issue.

```
~ % go tool pprof https+insecure://localhost:8443/debug/pprof/heap
Fetching profile over HTTP from https+insecure://localhost:8443/debug/pprof/heap
Handling connection for 8443
File: traefik
Type: inuse_space
Time: Jun 22, 2021 at 3:01pm (CDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 20
Showing nodes accounting for 2569.98MB, 85.67% of 2999.88MB total
Dropped 266 nodes (cum <= 15MB)
Showing top 20 nodes out of 118
      flat  flat%   sum%        cum   cum%
  914.97MB 30.50% 30.50%   914.97MB 30.50%  regexp/syntax.(*compiler).inst (inline)
  187.71MB  6.26% 36.76%   187.71MB  6.26%  github.com/gorilla/mux.(*Router).NewRoute
  171.70MB  5.72% 42.48%   171.70MB  5.72%  regexp.onePassCopy
  170.02MB  5.67% 48.15%   170.02MB  5.67%  github.com/vulcand/oxy/utils.CopyURL
  124.02MB  4.13% 52.28%  1428.71MB 47.63%  regexp.compile
  110.03MB  3.67% 55.95%   110.03MB  3.67%  github.com/traefik/traefik/v2/pkg/config/runtime.NewConfig
   92.51MB  3.08% 59.03%    92.51MB  3.08%  github.com/traefik/traefik/v2/pkg/config/dynamic.(*Router).DeepCopy (inline)
   79.51MB  2.65% 61.68%    84.51MB  2.82%  github.com/traefik/traefik/v2/pkg/middlewares/metrics.NewServiceMiddleware
   75.01MB  2.50% 64.19%    75.01MB  2.50%  regexp/syntax.(*parser).maybeConcat
      75MB  2.50% 66.69%       75MB  2.50%  github.com/traefik/traefik/v2/pkg/middlewares/accesslog.NewFieldHandler
   73.46MB  2.45% 69.13%   165.97MB  5.53%  github.com/traefik/traefik/v2/pkg/server.applyModel
   72.51MB  2.42% 71.55%    72.51MB  2.42%  github.com/vulcand/oxy/roundrobin.New
   61.51MB  2.05% 73.60%  1525.72MB 50.86%  github.com/gorilla/mux.newRouteRegexp
   60.50MB  2.02% 75.62%    60.50MB  2.02%  strings.(*Builder).grow
   59.50MB  1.98% 77.60%    59.50MB  1.98%  github.com/traefik/traefik/v2/pkg/server/provider.MakeQualifiedName
   53.50MB  1.78% 79.39%    53.50MB  1.78%  github.com/traefik/traefik/v2/pkg/server/service.buildProxy
      53MB  1.77% 81.15%       53MB  1.77%  github.com/gorilla/mux.(*Route).getRegexpGroup
   50.50MB  1.68% 82.84%    65.01MB  2.17%  github.com/gorilla/mux.(*Route).Subrouter
      46MB  1.53% 84.37%       60MB  2.00%  regexp.makeOnePass.func1
      39MB  1.30% 85.67%       39MB  1.30%  go/scanner.(*Scanner).scanRawString
```

**Comment by dr-travis** [comment]
Has this issue been solved? I observed similar trends with 2.4.8.

**Comment by orirawlings** [comment]
I'm able to reproduce with 2.4.8 on a Kubernetes cluster with a very large number of Ingress x Host/Path rules x backend pod replicas combinations. Quite a few of our Ingress hosts require HostRegexp rules.

I'm not so sure it is a leak per see.

We were using mostly default configurations from https://github.com/traefik/traefik-helm-chart. Notably default, unlimited timeouts for:

- `serverstransport.forwardingTimeouts.responseHeaderTimeout`
- `entryPoints.web.transport.respondingTimeouts.readTimeout`
- `entryPoints.web.transport.respondingTimeouts.writeTimeout`
- `entryPoints.websecure.transport.respondingTimeouts.readTimeout`
- `entryPoints.websecure.transport.respondingTimeouts.writeTimeout`

To reproduce we were forcing frequent routing configuration updates by deleting pods (routing targets) in our cluster and letting them be recreated. By default, traefik throttles observing configuration reloads to at most once every 2 seconds (`providers.providersThrottleDuration=2s`).

**Comment by orirawlings** [comment]
Setting timeout values for:

- `serverstransport.forwardingTimeouts.responseHeaderTimeout`
- `entryPoints.web.transport.respondingTimeouts.readTimeout`
- `entryPoints.web.transport.respondingTimeouts.writeTimeout`
- `entryPoints.websecure.transport.respondingTimeouts.readTimeout`
- `entryPoints.websecure.transport.respondingTimeouts.writeTimeout`

seems to have helped for my use case, but I still see a gradual increase in memory until an eventual OOM (it is just slower to manifest now).

I am seeing this log message though (and some other similar messages while reading service response bodies):
```
reverseproxy.go:480: httputil: ReverseProxy read error during body copy: unexpected EOF
```

My suspicion is that we're occasionally seeing long delays reading response bodies from upstream services before the above error occurs and is logged. In turn, we're keeping references to old versions of routing configuration live in the heap and this accumulates. As far as I can tell, there isn't a way to configure a timeout for this portion of proxying, but maybe someone can point me to some setting that I'm overlooking? Is there a way to set an overall timeout for the entire time spent proxying a request through traefik? Maybe on a top-level context?

**Comment by rtribotte** [comment]
Hello @orirawlings,

For timeout settings regarding communication with upstream services, there are only the `serversTransport` timeout options.
As you may already see, you can also configure the dial timeout: `serverstransport.forwardingTimeouts.dialTimeout`.

But as far as is understand your need, there is indeed no global timeout option, that would allow interrupting the response body read after a certain duration.

**Comment by rtribotte** [comment]
@orirawlings Nonetheless the `transport.respondingTimeouts.writeTimeout` option should be sufficient to cancel the context of the request to the upstream service.
What configuration values have you tried?

**Comment by krzysztof-bronk** [comment]
I've had all those timeouts specified since start, and there definitely still is a leak (possibly a slower one thanks to that but still)

**Comment by orirawlings** [comment]
@rtribotte I can confirm I'm setting the following timeouts:
```
          - --serverstransport.forwardingTimeouts.responseHeaderTimeout=300s
          - --entryPoints.web.transport.respondingTimeouts.readTimeout=300s
          - --entryPoints.web.transport.respondingTimeouts.writeTimeout=300s
          - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=300s
          - --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300s
```

**Comment by orirawlings** [comment]
At this point, I'm a bit stumped about what the problem might be. I added some additional logging around recovered panics, including some additional metadata about duration. I do all of my panicked request handlers taking less 301 seconds.

I'm attaching a heap profile from one of our instances after we stopped sending it requests to proxy. It didn't start leaking memory until we sent it requests, but even after we turned off requests, the memory remains elevated. Prior to sending it requests, the memory remained low for several days.

This is a blocker for us for adopting traefik v2, and considering looming incompatibilities between traefik v1 and newer Kubernetes versions due to the removal of beta Ingress API versions, this might force us to abandon traefik in lieu of a different Ingress controller implementation. 😞 

[2021-08-03-20:52:22-heap.pprof.zip](https://github.com/traefik/traefik/files/6927114/2021-08-03-20.52.22-heap.pprof.zip)

**Comment by orirawlings** [comment]
For comparison, I'm attaching a second heap profile from an instance after it has been restarted and before it serves any requests (aside from health checks). I.e. prior to it exhibiting any leak.

The Ingress configurations and Endpoints in our Kubernetes clusters are very similar to when I captured the heap profile in my previous comment. But as one can see, the heap is about 4 times larger and seems to be retaining about 4 times the amount of Routers. Because the Ingress configuration in the API is roughly the same, I wouldn't expect the corresponding Routers to occupy 4x the amount of heap space. It seems to me like we've leaked 3-4 references to old Router versions (provider will trigger a rebuild of a new Router version as often as every 2 seconds, if there are updates in the Kubernetes APIs). Short of capturing a core dump, I'm not sure the best way to narrow down where the references might be escaping.

I'm still trying to figure out a sensible way to trigger and preserve a core dump for a traefik replica running in Kubernetes, but if it is fruitful I'll try updating this issue with more information.

[2021-08-04-20:05:56-heap.pprof.zip](https://github.com/traefik/traefik/files/6934148/2021-08-04-20.05.56-heap.pprof.zip)

**Comment by orirawlings** [comment]
So I've started capturing core dumps from leaking traefik replicas. I'm able to open them up with [delve](https://github.com/go-delve/delve) and poke around, but I'm scratching my head a bit with how to explore the object reference graph to narrow down what might be keeping certain large objects alive in the heap. In a prior life as a Java developer, I would have used something like [Eclipse Memory Analyzer](https://www.eclipse.org/mat/), but I'm having trouble finding any kind of equivalent for the Go ecosystem.

Go heap profiles are nice, but they really only point to where the objects are being allocated in the code. I'm assuming the problem I'm seeing here is with references to these objects escaping to other areas of the code that keep them alive. The profile and pprof tools don't seem to be pointing towards those other areas of the code unless I'm missing something.

**Comment by dhyanio** [comment]
Is their any progress in this issue. ?

**Comment by mpl** [comment]
@dhyanio we have not forgotten about it, but since we cannot reproduce it, it is very hard for us to pinpoint the problem, let alone fix it. It would greatly help if someone could contribute an easily runnable case/environment so we can reproduce it ourselves.

**Comment by dhyanio** [comment]
@mpl we are a leading opensource startup. we are completely relying on traefik and initially faced very high memory issues. After upgrading to 2.2.X now facing a very high cpu. Can you please suggest to me what is the best version for us?

**Comment by mpl** [comment]
@dhyanio Using the latest version is the best way for us to be able to debug the issue, if you can give us a reproducible case.

**Comment by farmerluo** [comment]
traefik lastest version: 2.5.4

<img width="1314" alt="图片" src="https://user-images.githubusercontent.com/1650698/146039767-e4238d40-fe6c-45c9-af3e-c51a8d9ce9f1.png">

<img width="1351" alt="图片" src="https://user-images.githubusercontent.com/1650698/146040145-ebcb5fa3-f68b-4054-9968-45511b68e534.png">

**Comment by mpl** [comment]
@kungfukennyg 

We were able to reproduce a memory leak, but the circumstances are closer to what is described in #7964 , so we don't know if this will apply to you, but:
we pushed a work-around to the v2.5 experimental image (https://hub.docker.com/layers/traefik/traefik/experimental-v2.5/images/sha256-73242275482292255a04ebfb1f4d62034d8119983721e72e7175150b1bda7387?context=explore), so you could always try to see if it helps with your problem.
docker pull traefik/traefik:experimental-v2.5

Please let us know if that leads to any additional information.

**Comment by kungfukennyg** [comment]
We've done some testing with version `2.5.7` (which I assume, based on the release logs, contains the memory leak fix you mentioned on branch `experimental-v2.5`) and sadly are still seeing the same leaky behavior.

**Comment by mpl** [comment]
Are you actually seeing the symptoms with the same amplitude as before? have they not been lowered at all?

> We've done some testing with version `2.5.7` (which I assume, based on the release logs, contains the memory leak fix you mentioned on branch `experimental-v2.5`) and sadly are still seeing the same leaky behavior.

**Comment by tfny** [comment]
Hiya!  We just merged [PR 8706](https://github.com/traefik/traefik/pull/8706), which we think fixed this in v2.  Would y'all check for us and give us feedback?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
