### ISSUE TITLE
redis Provider will not update rules when "unexpected EOF" error happened

### ISSUE THREAD

**Issue by bstr9** [traefik/traefik#9212]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi, current we use redis as Provider and update redis rule dynamic. But we found a problem is that, when we update route rule(or any other redis keys) very frenquently, may caused redis "unexpected EOF" error happend. This will cause traefik won't update rules any more.

### What did you see instead?

So I digest the problem from [kvtools/valkerie](https://github.com/kvtools/valkeyrie/blob/0bf7d50195f55baef38afda33940b17248dbd990/store/redis/redis.go#L520;)'s code here. 
```golang
func (s *subscribe) receiveLoop(ctx context.Context, msgCh chan *redis.Message) {
	defer close(msgCh)

	for {
		select {
		case <-s.closeCh:
			return
		case <-ctx.Done():
			return
		default:
			msg, err := s.pubsub.ReceiveMessage(ctx)
			if err != nil {
				return
			}
			if msg != nil {
				msgCh <- msg
			}
		}
	}
}
```
When s.pubsub.ReceiveMessage(ctx) returns error, the goroutine will exited and close the message channel: msgCh.
However the error will not notify the upper user [code here](https://github.com/kvtools/valkeyrie/blob/0bf7d50195f55baef38afda33940b17248dbd990/store/redis/redis.go#L214).
Finally, treafik still waiting the notify from the "events" [channel](https://github.com/traefik/traefik/blob/c9520480c2c70935817bedac1e8a3e9eaacf2f86/pkg/provider/kv/kv.go#L117).

```golang
func (p *Provider) watchKv(ctx context.Context, configurationChan chan<- dynamic.Message) error {
	operation := func() error {
		events, err := p.kvClient.WatchTree(p.RootKey, ctx.Done(), nil)
		if err != nil {
			return fmt.Errorf("failed to watch KV: %w", err)
		}

		for {
			select {
			case <-ctx.Done():
				return nil
			case _, ok := <-events:
				if !ok {
					return errors.New("the WatchTree channel is closed")
				}

				configuration, errC := p.buildConfiguration()
				if errC != nil {
					return errC
				}

				if configuration != nil {
					configurationChan <- dynamic.Message{
						ProviderName:  p.name,
						Configuration: configuration,
					}
				}
			}
		}
	}

	notify := func(err error, time time.Duration) {
		log.FromContext(ctx).Errorf("KV connection error: %+v, retrying in %s", err, time)
	}

	err := backoff.RetryNotify(safe.OperationWithRecover(operation),
		backoff.WithContext(job.NewBackOff(backoff.NewExponentialBackOff()), ctx), notify)
	if err != nil {
		return fmt.Errorf("cannot connect to KV server: %w", err)
	}
	return nil
```

Anyone can fix the problem, or just I create a pull request to fix the problem.

### What version of Traefik are you using?

v2.8.1

### What is your environment & configuration?

```
global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  insecure: true
  dashboard: true
entryPoints:
  portal:
    address: ":30888"
porviders:
  providersThrottleDuration: 0.5s
  docker:
    swarmMode: false
    network: true
    exposedByDefault: false
  redis:
    rootKey: 'TRAEFIK_CONFIG'
    endpoints:
      - 'xx.xx.xx.xx:6379'
log:
    level: DEBUG
    format: json
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @bstr9,

Thanks for reporting this!

After taking a look at the code you pointed out, we think that the bug is related to valkeyrie and not Traefik.
It looks like the `watchCh` chan should be close here https://github.com/kvtools/valkeyrie/blob/0bf7d50195f55baef38afda33940b17248dbd990/store/redis/redis.go#L211.

> Anyone can fix the problem, or just I create a pull request to fix the problem.

As this is not related to Traefik, we are closing this issue, but we gladly welcome any contribution, so please open a pull request on the kvtools/valkeyrie side to fix the issue.

**Comment by rtribotte** [comment]
After a second thought, we are reopening this issue to keep track of that bug, until of the update of the valkeyrie dependency once https://github.com/kvtools/valkeyrie/pull/70 will be merged.

**Comment by bstr9** [comment]
Thanks @rtribotte. It seems fixed now.

**Comment by rtribotte** [comment]
Hello @bstr9,

I am reopening the issue to keep track of this because until the update of the dependency to valkeyrie the problem is not yet fixed for Traefik.

**Comment by traefiker** [comment]
Closed by #9243.
